<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE futbol [
<!ELEMENT futbol ((jugador|equipo)*)>
<!ELEMENT jugador EMPTY>
<!ATTLIST jugador nombre NMTOKENS #REQUIRED>
<!ATTLIST jugador codigo ID #REQUIRED>
<!ELEMENT equipo EMPTY>
<!ATTLIST equipo nombre CDATA #REQUIRED>
<!ATTLIST equipo jugadores IDREFS #IMPLIED>
]>
<futbol>
<jugadores>
<jugador> nombre="Alfredo Di Stéfano" codigo="ads"</jugador>
<jugador> nombre="Edison Arantes do Nascimento" codigo="ean"</jugador>
<jugador> nombre="Diego Armando Maradona" codigo="dam"</jugador>
<jugador> nombre="Johan Cruyff" codigo="jc"</jugador>
<equipo> nombre="Società Sportiva Calcio Napoli" jugadores="Maradona"</jugador>
<equipo> nombre="Futbol Club Barcelona" jugadores="Cruyff, Maradona"</jugador>
</jugadores>
</futbol>